### registrar usuario ###
POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "juan",
    "password": "12354",
    "rols": ["USER"]
}

### hacer login del usuario ###

POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "juan",
    "password": "12345"
}