### registrar usuario ###
POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "carlos",
    "password": "12345"
}

### hacer login del usuario ###

POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json
Cookie:AUTH_TOKEN=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjYXJsb3MiLCJyb2xzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3NjI1MzQyNDQsImV4cCI6MTc2MjUzNzg0NH0.wgz_z6AE1Iw2HYg7H4EYhqFjSw41H0nuNCCW6ySBJVHne7BhmEiS2LrJ13OyWaKAt3IsuqMAaBpPbDIkTR4LIQ

{
    "username": "carlos",
    "password": "12345"
}

### testear los roles y autorizaciones
GET  http://localhost:8080/api/auth HTTP/1.1
Content-Type: application/json
