### registrar usuario ###
POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "jose",
    "password": "12345"
}

### hacer login del usuario ###

POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json
Cookie:AUTH_TOKEN=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb3NlIiwicm9scyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNzYyNzI4MjkyLCJleHAiOjE3NjI3MzE4OTJ9._W3DI82DI9OfpJsnC_r8S9x4pAvDCj5KuOCmoAS8iwr5aVByI8RwlsGfINmSS1CzK9IdXGRR9n05QN8FGzrOSQ

{
    "username": "pablo",
    "password": "12345"
}

### testear los roles y autorizaciones
GET  http://localhost:8080/api/auth HTTP/1.1
Content-Type: application/json