### registrar usuario ###
POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "carlos",
    "password": "12345"
}

### hacer login del usuario ###

POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json
Cookie:AUTH_TOKEN=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjYXJsb3MiLCJyb2xzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3NjMzMDM1MjIsImV4cCI6MTc2MzMwNzEyMn0.Y9gAUVxULYeSY01HIDe1b02en2r5NK6ZsLmQCviSnincsJbmROxGyU2c8bSXhslxcBXTk1HsZEWG2i8RHxa29g

{
    "username": "carlos",
    "password": "12345"
}

### testear los roles y autorizaciones
GET  http://localhost:8080/api/auth HTTP/1.1
Content-Type: application/json