spring.application.name=ToDo


spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/ToDo
spring.datasource.username=br7forlife
spring.datasource.password=1043300860
spring.datasource.driver-class-name=org.postgresql.Driver


jwt.secret.key=this-is-example-for-json-web-tok
